### ISSUE TITLE
Installation instructions missing fftw

### ISSUE THREAD

**Issue by thomasaarholt** [Ivanlh20/MULTEM#10]
I get an error, missing `libfftw3f-3.dll` and `libfftw3-3.dll`, which is not mentioned in the installation instructions.

**Comment by thomasaarholt** [comment]
The solution was to download the fftw3 package, and move the following files into `/Windows/Sysmte32`:
`libfftw3-3.dll`
`libfftw3f-3.dll`
`libfftw3l-3.dll.`

**Comment by chenspc** [comment]
**macOS:**
Solution 1. Install [Homebrew](http://docs.brew.sh/Installation.html), then open Terminal.app and type in the brew command after the prompt ($)
`$ brew install fftw`
Solution 2. (Not tested) Similar to the Windows solution, there is a [Mac Installation Notes](http://www.fftw.org/install/mac.html) page from fftw.org.

**Comment by Quantumstud** [comment]
Comparing with the provided precompiled mex_bin files and the post-self-compiled generated mex_bin files. I find the all the library files missing in the post-self-compiled mex_bin files. These library files are mostly CUDA library files and fftw3 library files. I also noticed il_atom_radius and il_atom_type is also missing in the self-compiled mex_bin files. 
I could solve the library just by copying the .dll files from the pre-compiled mex_bin folder. I am not sure how will it affect the speed of the software. I assume these dependencies weren't taken into account during the compilation. 
Furthermore, any idea what would be the impact of missing il_atom_radius and il_atom_type?

**Comment by thomasaarholt** [comment]
I did not encounter the above issues, as far as I remember.
