### ISSUE TITLE
Which part of a sample interacts with the beam first?

### ISSUE THREAD

**Issue by thomasaarholt** [Ivanlh20/MULTEM#21]
If a "pretend" sample has two atoms, A and B, with z = 0 and 5 Å respectively, which atom will be hit by the beam first?

Another way of asking the same question is, "is the sample sat with the z-axis increasing towards the electron gun, or increasing away from the gun"?

Stealing @cophus excellent image from prism-em/prismatic#33:
![image](https://user-images.githubusercontent.com/2721423/48470457-c56a1b00-e7f1-11e8-8559-41141bb9e05b.png)

This is important for my application.

**Comment by Ivanlh20** [comment]
Hi Thomas, the atom A will be hit first by the beam.

**Comment by thomasaarholt** [comment]
Great, thanks!
