### ISSUE TITLE
Cuda 9/10?

### ISSUE THREAD

**Issue by thomasaarholt** [Ivanlh20/MULTEM#23]
The IT department is wanting researchers to play on their new GPU nodes, which consist of 28 CPU cores, 128 GiB RAM and 4 x NVIDIA RTX 2080 Ti cards, running Ubuntu 16.

For now they only have CUDA 9/10, with no SLURM/module loading system.

~~Is GCC a necessary requirement?~~ GCC is available. Has anyone tried compiling with CUDA 9/10? Or am I best off contacting IT and asking them to install the necessary software? I will already need them to install CMake, for instance, so I will be contacting them nonetheless.

**Comment by thomasaarholt** [comment]
Sorry, CMake is not necessary for MULTEM - I just assumed.

**Comment by Quantumstud** [comment]
Were you successful in running the code in the cluster? I too have some GPU hours and wanted to run this package in a cluster but after several attempts have been unable to do so.

**Comment by ningustc** [comment]
If the Thrust library is not removed from MULTEM, the support for CUDA version over 9.2 always fails.

**Comment by thomasaarholt** [comment]
Could you clarify that?

**Comment by ningustc** [comment]
You can write a simple test using cuda9.2, include the thrust header files, and call the function raw_pointer_cast<>. 
In my package, I remove all the things related to thrust.
