### ISSUE TITLE
See incident STEM probe used in a simulation?

### ISSUE THREAD

**Issue by emichr** [Ivanlh20/MULTEM#28]
Is there a way to retrieve the incident probe that was used during a STEM simulation? Alternatively, is there a way to reproduce the probe?

**Comment by Ivanlh20** [comment]
Check out the example https://github.com/Ivanlh20/MULTEM/blob/master/mex_examples_multem/example_incident_wave_1.m
Do not forget to use option 2 to visualize a convergent beam
input_multislice.iw_type = 2;   % 1: Plane_Wave, 2: Convergent_wave, 3:User_Define, 4: auto

**Comment by emichr** [comment]
Great, thanks!

If I include the lines
`input_multislice.iw_type = 2;`
`input_multislice.iw_psi = read_psi_0_multem(input_multislice.nx, input_multislice.ny);` 
in my script before running my STEM simulations, will the `input_multislice.iw_psi` be used as the input wave for each pixel in the simulation? In other words, if I make changes to `input_multislice.iw_psi`, and then run my simulation with `input_multislice.simulation_type = 11`, will the simulation use the wave in `input_multislice.iw_psi` or will it generate a new incident wave based on the other parameters in `input_multislice`?

**Comment by Ivanlh20** [comment]
if you want to use a user define input wave function, then you have to set

input_multislice.iw_type = 3; % 1: Plane_Wave, 2: Convergent_wave,
3:User_Define, 4: auto

and you have to define your own input wave as a complex matrix as

input_multislice.iw_psi = "Complex matrix";

Check out this example
https://github.com/Ivanlh20/MULTEM/blob/master/mex_examples_multem/example_incident_wave_2.m
 There I use a user define input wave

This option won't take into account the input parameter of the condenser
lens.

**Comment by emichr** [comment]
Ah, of course! Thank you for clearing that up.
