### ISSUE TITLE
Potential slicing

### ISSUE THREAD

**Issue by emichr** [Ivanlh20/MULTEM#30]
I have some questions about slicing when using `ePS_dz_Proj` potential slicing in MULTEM. That I hope is relatively straight forward to answer.

First of all, is the first slice defined to be from _z=0_ to _z=dz_? or from _z=-dz/2_ to _z=dz/2_?. I.e. will an atom positioned at _z=0_ be situated in the middle of a slice, or at the boundary of a slice? If the latter case, should one offset atoms in order to make a slice belong to one atomic plane alone?

Secondly, is the slice thickness `spec_dz` defined as the complete slice thickness, or the half-thickness of the slice? This will of course be connected to the first question.

I've made a quick and dirty figure below to try to illustrate what I mean. 

![slicing](https://user-images.githubusercontent.com/16645501/57306829-ca928d80-70e3-11e9-9d60-8d77b463f8e9.png)

If I've misunderstood something about how MULTEM computes or uses the slices, please let me know.

**Comment by Ivanlh20** [comment]
Check out the following examples.

https://github.com/Ivanlh20/MULTEM/blob/master/mex_examples_multem/example_specimen_planes.m


https://github.com/Ivanlh20/MULTEM/blob/master/mex_examples_multem/example_specimen_slicing_show.m



https://github.com/Ivanlh20/MULTEM/blob/master/mex_examples_multem/example_specimen_slicing_zone_axis.m

**Comment by emichr** [comment]
Thanks for your help!

By playing around with parameters in the examples, it seems that the first slice is centered on _z=0_, and `spec_dz` is the full slice thickness (although some of the slices are sometimes thicker when needed, e.g. the first slice has thickness 5.78 Å in `example_specimen_slicing_zone_axis` when modified with `input_multislice.potential_slicing = 2` and `spec_dz=5`).
