### ISSUE TITLE
Temperature in examples

### ISSUE THREAD

**Issue by emichr** [Ivanlh20/MULTEM#31]
I was wondering, what temperature does the value of ´rms3d´ used in the example files, e.g. in ´example_MULTEM_STEM´ correspond to?

**Comment by Ivanlh20** [comment]
Check out page 4

https://github.com/Ivanlh20/MULTEM/blob/master/tutorial/Emat_workshop.pdf

**Comment by emichr** [comment]
Thanks for your quick reply! 

I've checked out the EMAT worksheet, but I can't see any information about what temperature the specific rms3d value corresponds to. It's not that important to know the temerature in the examples for me, but I want to understand these examples to understand how to set up simulations correctly.

A value of _rms3d=0.085_ Å corresponds to a debye waller factor of _0.5704_ Å^2. Comparing this value to tabulated Debye Waller factors for gold in e.g. [Peng, Ren, Dudarev, and Whelan, Acta Cryst. (1996), A52, 456-470](https://doi.org/10.1107/S010876739600089X), the value of _rms3d=0.085_ Å used in the MULTEM examples should correspond to a temerature of about _270_ K, around _0_ C. Is this correct?
