### ISSUE TITLE
Use of through Thickness calculation

### ISSUE THREAD

**Issue by Quantumstud** [Ivanlh20/MULTEM#33]
In MULTEM, there is an option to calculate using through "Thickness" under the Thickness tab. [Please see the attached Image]. I have a doubt regarding this option. 
Does this option directly gives us the value of $ | \psi |^2 $ (square Modulus of the wavefunction) at each thickness value? If not is there any way in MULTEM to obtain the modulus of the wavefunction?
![image](https://user-images.githubusercontent.com/39451156/63769013-48351000-c904-11e9-84fe-59b718a0d939.png)

**Comment by Quantumstud** [comment]
I wanted to calculate the square of the modulus of the wavefunction of the electron inside the specimen. Is there any example for calculation of the modulus of the wavefunction in the STEM mode within the multislice framework in MULTEM?

**Comment by ThFriedrich** [comment]
Hello,

> Does this option directly gives us the value of $ | \psi |^2 $ (square Modulus of the wavefunction) at each thickness value? 

.. so the answer is: yes, it does. If you'd consider using the matlab functions (I would recommend doing so), rather than the GUI, you can check for example: 

https://github.com/Ivanlh20/MULTEM/blob/master/mex_examples_multem/example_MULTEM_HRTEM.m

The same principle applies to STEM mode as well. There is also an example on GitHub:

https://github.com/Ivanlh20/MULTEM/blob/master/mex_examples_multem/example_MULTEM_STEM.m

I hope that helps.

**Comment by Quantumstud** [comment]
Hi @ThFriedrich! Thank you so much for your prompt reply and your suggestion regarding the MATLAB. I currently use MATLAB to run the simulations.

I think that the through-thickness calculates the square of the modulus of the wavefunction and then integrates it over the detector. I see that the value different for the different detectors. 

In principle, I wanted to achieve something like this using MULTEM (picture)! This Image is taken from G.T. Martinez et al.  Ultramicroscopy 187 (2018) 84–92.  Here the probe is just at one point and then throughout the specimen, the probability of the electron wave is calculated. I want to the propagation of the electron through the specimen. 

Many thanks for your suggestions. Can you suggest how this can be achieved?

![Capture](https://user-images.githubusercontent.com/39451156/63788908-dd4a0000-c928-11e9-8a7e-8910fb36625c.JPG)

**Comment by ThFriedrich** [comment]
Indeed, in STEM Mode you get the integration over any given detector. To get the wave function you can use the EWRS mode. You can check the example:

https://github.com/Ivanlh20/MULTEM/blob/master/mex_examples_multem/example_MULTEM_EWRS.m 

You just have to change the incident wave type to convergent wave and adjust the probe position  like:
`input_multislice.iw_type = 2;                                      % 1: Plane_Wave, 2: Convergent_wave, 3:User_Define, 4: auto
input_multislice.iw_psi = 0;                                        % user define incident wave
input_multislice.iw_x = input_multislice.spec_lx/2;     % x position 
input_multislice.iw_y = input_multislice.spec_ly/2;     % y position`

**Comment by Quantumstud** [comment]
Dear @ThFriedrich ,
Thanks a lot! I was fixated on the example_propagate.m and completely missed the EWRS example. This is exactly what I wanted. Thank you very much!
