### ISSUE TITLE
Support for higher CUDA versions (>8.0)

### ISSUE THREAD

**Issue by Quantumstud** [Ivanlh20/MULTEM#39]
Hi,
MULTEM only works for CUDA 8.0. However, CUDA 8.0 has reached its end of life and it has a lot of trouble installing in the newer versions of OS such as Ubuntu 18.04 and 20.04. Is there a new version for MULTEM which works in a higher CUDA version such as 9 or above? Is anyone working on that development?
Thank you.

**Comment by ThFriedrich** [comment]
Hello,
you can use Multem with higher versions of CUDA. What is actually incompatible is the thrust library, which you can find in the CUDA-includes (/usr/local/cuda-8.0/include/thrust). I am running Multem with CUDA 10.0 on Ubuntu 18.04. I only copied the old (v8) thrust folder into /usr/local/cuda-10.0/include/thrust and renamed the one that was there (just to keep it around). That works for me. There is also a new (major) version of MULTEM under development which will be compatible with later CUDA versions by default, but there is no release date set yet. In the meantime, the workaround described above may help.
